using namespace std;

#include<iostream>
#include<fstream>
#include<string>
#include <sys/time.h>
#include<math.h>
#include "bdd.h"
#include "bvec.h"



bool display_debug; //output the debug info.
bool display_least; //output the least info.

bool writeFile; //output the backtracking info. to result.txt


//************The info. about the Petri net!*******************
//Note that if makespan may exceed 255, MAXNUMBER and MAXBITS need to be revised!
//The incidence matrix generated by INA is transposed!

/*
char source_net[50]="new4x3_1111";  //The name of the Petri net.
#define NP 31  //number of places!
#define NT 24  //number of transitions!
#define MAXNUMBER 255 // the largest number of the totol makespan, tokens in a place, remaining time in a place, and the ID of a transition.
#define MAXBITS 8 // the number of bits representing the above information such that MAXBITS=RoundUp(log_2(MAXNUMBER+1)).
const bool isIncidenceMatrix = false;  //If the inputed incidence matrix is not transposed, isIncidenceMatrix=true; otherwise, isIncidenceMatrix=false.
int h3pj[]={6,11,16,23};//The ID numbers of places in H_l(p_max) for h_BDD where j is started from 1. H_l(p_max) denotes the loyal holders of p_max that is a resource place whose processing time of its loyal holders is maximal among all 1-bounded resource places.
int h3_0=16; //h_BDD(S_0)  16=4+5+5+2
int P_R[]={29,30,31}; //The IDs of resource places, started from 1.
*/


/*
char source_net[50]="new4x3_2111";  //The name of the Petri net.
#define NP 31  //number of places!
#define NT 24  //number of transitions!
#define MAXNUMBER 255 // the largest number of the totol makespan, tokens in a place, remaining time in a place, and the ID of a transition.
#define MAXBITS 8 // the number of bits representing the above information such that MAXBITS=RoundUp(log_2(MAXNUMBER+1)).
const bool isIncidenceMatrix = false;  //If the inputed incidence matrix is not transposed, isIncidenceMatrix=true; otherwise, isIncidenceMatrix=false.
int h3pj[]={6,11,16,23};//The ID numbers of places in H_l(p_max) for h_BDD where j is started from 1. H_l(p_max) denotes the loyal holders of p_max that is a resource place whose processing time of its loyal holders is maximal among all 1-bounded resource places.
int h3_0=20; //h_BDD(S_0)  =4*2+5+5+2
int P_R[]={29,30,31}; //The IDs of resource places, started from 1.
*/


/*
char source_net[50]="new4x3_2211";  //The name of the Petri net.
#define NP 31  //number of places!
#define NT 24  //number of transitions!
#define MAXNUMBER 255 // the largest number of the totol makespan, tokens in a place, remaining time in a place, and the ID of a transition.
#define MAXBITS 8 // the number of bits representing the above information such that MAXBITS=RoundUp(log_2(MAXNUMBER+1)).
const bool isIncidenceMatrix = false;  //If the inputed incidence matrix is not transposed, isIncidenceMatrix=true; otherwise, isIncidenceMatrix=false.
int h3pj[]={6,11,16,23};//The ID numbers of places in H_l(p_max) for h_BDD where j is started from 1. H_l(p_max) denotes the loyal holders of p_max that is a resource place whose processing time of its loyal holders is maximal among all 1-bounded resource places.
int h3_0=25; //h_BDD(S_0)  =4*2+5*5+5+2
int P_R[]={29,30,31}; //The IDs of resource places, started from 1.
*/


/*
char source_net[50]="new4x3_2221";  //The name of the Petri net.
#define NP 31  //number of places!
#define NT 24  //number of transitions!
#define MAXNUMBER 255 // the largest number of the totol makespan, tokens in a place, remaining time in a place, and the ID of a transition.
#define MAXBITS 8 // the number of bits representing the above information such that MAXBITS=RoundUp(log_2(MAXNUMBER+1)).
const bool isIncidenceMatrix = false;  //If the inputed incidence matrix is not transposed, isIncidenceMatrix=true; otherwise, isIncidenceMatrix=false.
int h3pj[]={6,11,16,23};//The ID numbers of places in H_l(p_max) for h_BDD where j is started from 1. H_l(p_max) denotes the loyal holders of p_max that is a resource place whose processing time of its loyal holders is maximal among all 1-bounded resource places.
int h3_0=30; //h_BDD(S_0)  =4*2+5*5+5*5+2
int P_R[]={29,30,31}; //The IDs of resource places, started from 1.
*/

/*
char source_net[50]="new4x3_2222";  //The name of the Petri net.
#define NP 31  //number of places!
#define NT 24  //number of transitions!
#define MAXNUMBER 255 // the largest number of the totol makespan, tokens in a place, remaining time in a place, and the ID of a transition.
#define MAXBITS 8 // the number of bits representing the above information such that MAXBITS=RoundUp(log_2(MAXNUMBER+1)).
const bool isIncidenceMatrix = false;  //If the inputed incidence matrix is not transposed, isIncidenceMatrix=true; otherwise, isIncidenceMatrix=false.
int h3pj[]={6,11,16,23};//The ID numbers of places in H_l(p_max) for h_BDD where j is started from 1. H_l(p_max) denotes the loyal holders of p_max that is a resource place whose processing time of its loyal holders is maximal among all 1-bounded resource places.
int h3_0=32; //h_BDD(S_0)  =4*2+5*5+5*5+2*2
int P_R[]={29,30,31}; //The IDs of resource places, started from 1.
*/


/*
char source_net[50]="Xiong981111";  //The name of the Petri net.
#define NP 31  //number of places!
#define NT 24  //number of transitions!
#define MAXNUMBER 255 // the largest number of the totol makespan, tokens in a place, remaining time in a place, and the ID of a transition.
#define MAXBITS 8 // the number of bits representing the above information such that MAXBITS=RoundUp(log_2(MAXNUMBER+1)).
const bool isIncidenceMatrix = false;  //If the inputed incidence matrix is not transposed, isIncidenceMatrix=true; otherwise, isIncidenceMatrix=false.
int h3pj[]={6,9,18,25};//The ID numbers of places in H_l(p_max) for h_BDD where j is started from 1.
int h3_0=17; //h_BDD(S_0)  17=4+4+5+4
int P_R[]={29,30,31}; //The IDs of resource places, started from 1.
*/


/*
char source_net[50]="Xiong982111";  //The name of the Petri net.
#define NP 31  //number of places!
#define NT 24  //number of transitions!
#define MAXNUMBER 255 // the largest number of the totol makespan, tokens in a place, remaining time in a place, and the ID of a transition.
#define MAXBITS 8 // the number of bits representing the above information such that MAXBITS=RoundUp(log_2(MAXNUMBER+1)).
const bool isIncidenceMatrix = false;  //If the inputed incidence matrix is not transposed, isIncidenceMatrix=true; otherwise, isIncidenceMatrix=false.
int h3pj[]={6,9,18,25};//The ID numbers of places in H_l(p_max) for h_BDD where j is started from 1.
int h3_0=25; //h_BDD(S_0), 17=4*2+4*2+5+4
int P_R[]={29,30,31}; //The IDs of resource places, started from 1.
*/




/*
char source_net[50]="Xiong982211";  //The name of the Petri net.
#define NP 31  //number of places!
#define NT 24  //number of transitions!
#define MAXNUMBER 255 // the largest number of the totol makespan, tokens in a place, remaining time in a place, and the ID of a transition.
#define MAXBITS 8 // the number of bits representing the above information such that MAXBITS=RoundUp(log_2(MAXNUMBER+1)).
const bool isIncidenceMatrix = false;  //If the inputed incidence matrix is not transposed, isIncidenceMatrix=true; otherwise, isIncidenceMatrix=false.
int h3pj[]={6,9,18,25};//The ID numbers of places in H_l(p_max) for h_BDD where j is started from 1.
int h3_0=21; //h_BDD(S_0) 17=4*2+4+5+4
int P_R[]={29,30,31}; //The IDs of resource places, started from 1.
*/




/*
char source_net[50]="Xiong98NoBuffer";  //The name of the Petri net.
bool isIncidenceMatrix = false;  //If the inputed incidence matrix is not transposed, isIncidenceMatrix=true; otherwise, isIncidenceMatrix=false.
#define NP 23  //number of places!
#define NT 16  //number of transitions!
#define MAXNUMBER 255 // the largest number of the totol makespan, tokens in a place, remaining time in a place, and the ID of a transition.
#define MAXBITS 8 // the number of bits representing the above information such that MAXBITS=RoundUp(log_2(MAXNUMBER+1)).
*/ 

/*
char source_net[50]="ChenFig511";  //The name of the Petri net.
#define NP 21  //number of places!
#define NT 14  //number of transitions!
#define MAXNUMBER 255 // the largest number of the totol makespan, tokens in a place, remaining time in a place, and the ID of a transition.
#define MAXBITS 8 // the number of bits representing the above information such that MAXBITS=RoundUp(log_2(MAXNUMBER+1)).
const bool isIncidenceMatrix = false;  //If the inputed incidence matrix is not transposed, isIncidenceMatrix=true; otherwise, isIncidenceMatrix=false.
int h3pj[]={2,5,11,13};//The ID numbers of places in H_l(p_max) for h_BDD where j is started from 1.
int h3_0=16; //h_BDD(S_0), 16=5+4+3+4
int P_R[]={14, 15, 16, 17, 18, 19}; //The IDs of resource places, started from 1.
*/


/*
char source_net[50]="ChenFig522";  //The name of the Petri net.
#define NP 21  //number of places!
#define NT 14  //number of transitions!
#define MAXNUMBER 255 // the largest number of the totol makespan, tokens in a place, remaining time in a place, and the ID of a transition.
#define MAXBITS 8 // the number of bits representing the above information such that MAXBITS=RoundUp(log_2(MAXNUMBER+1)).
const bool isIncidenceMatrix = false;  //If the inputed incidence matrix is not transposed, isIncidenceMatrix=true; otherwise, isIncidenceMatrix=false.
int h3pj[]={2, 5, 11, 13};//The ID numbers of places in H_l(p_max) for h_BDD where j is started from 1.
int h3_0=32; //h_BDD(S_0), 32=16*2
int P_R[]={14, 15, 16, 17, 18, 19}; //The IDs of resource places, started from 1.
*/


/*
char source_net[50]="ChenFig533";  //The name of the Petri net.
#define NP 21  //number of places!
#define NT 14  //number of transitions!
#define MAXNUMBER 255 // the largest number of the totol makespan, tokens in a place, remaining time in a place, and the ID of a transition.
#define MAXBITS 8 // the number of bits representing the above information such that MAXBITS=RoundUp(log_2(MAXNUMBER+1)).
const bool isIncidenceMatrix = false;  //If the inputed incidence matrix is not transposed, isIncidenceMatrix=true; otherwise, isIncidenceMatrix=false.
int h3pj[]={2, 5, 11, 13};//The ID numbers of places in H_l(p_max) for h_BDD where j is started from 1.
int h3_0=48; //h_BDD(S_0), =16*3
int P_R[]={14, 15, 16, 17, 18, 19}; //The IDs of resource places, started from 1.
*/

/*
char source_net[50]="ChenFig544";  //The name of the Petri net.
#define NP 21  //number of places!
#define NT 14  //number of transitions!
#define MAXNUMBER 255 // the largest number of the totol makespan, tokens in a place, remaining time in a place, and the ID of a transition.
#define MAXBITS 8 // the number of bits representing the above information such that MAXBITS=RoundUp(log_2(MAXNUMBER+1)).
const bool isIncidenceMatrix = false;  //If the inputed incidence matrix is not transposed, isIncidenceMatrix=true; otherwise, isIncidenceMatrix=false.
int h3pj[]={2, 5, 11, 13};//The ID numbers of places in H_l(p_max) for h_BDD where j is started from 1.
int h3_0=64; //h_BDD(S_0), =16*4
int P_R[]={14, 15, 16, 17, 18, 19}; //The IDs of resource places, started from 1.
*/


/*
char source_net[50]="ChenFig555";  //The name of the Petri net.
#define NP 21  //number of places!
#define NT 14  //number of transitions!
#define MAXNUMBER 255 // the largest number of the totol makespan, tokens in a place, remaining time in a place, and the ID of a transition.
#define MAXBITS 8 // the number of bits representing the above information such that MAXBITS=RoundUp(log_2(MAXNUMBER+1)).
const bool isIncidenceMatrix = false;  //If the inputed incidence matrix is not transposed, isIncidenceMatrix=true; otherwise, isIncidenceMatrix=false.
int h3pj[]={2, 5, 11, 13};//The ID numbers of places in H_l(p_max) for h_BDD where j is started from 1.
int h3_0=80; //h_BDD(S_0), =16*5
int P_R[]={14, 15, 16, 17, 18, 19}; //The IDs of resource places, started from 1.
*/

/*
char source_net[50]="ChenFig566";  //The name of the Petri net.
#define NP 21  //number of places!
#define NT 14  //number of transitions!
#define MAXNUMBER 255 // the largest number of the totol makespan, tokens in a place, remaining time in a place, and the ID of a transition.
#define MAXBITS 8 // the number of bits representing the above information such that MAXBITS=RoundUp(log_2(MAXNUMBER+1)).
const bool isIncidenceMatrix = false;  //If the inputed incidence matrix is not transposed, isIncidenceMatrix=true; otherwise, isIncidenceMatrix=false.
int h3pj[]={2, 5, 11, 13};//The ID numbers of places in H_l(p_max) for h_BDD where j is started from 1.
int h3_0=96; //h_BDD(S_0), =16*6
int P_R[]={14, 15, 16, 17, 18, 19}; //The IDs of resource places, started from 1.
*/

/*
char source_net[50]="ChenFig577";  //The name of the Petri net.
#define NP 21  //number of places!
#define NT 14  //number of transitions!
#define MAXNUMBER 255 // the largest number of the totol makespan, tokens in a place, remaining time in a place, and the ID of a transition.
#define MAXBITS 8 // the number of bits representing the above information such that MAXBITS=RoundUp(log_2(MAXNUMBER+1)).
const bool isIncidenceMatrix = false;  //If the inputed incidence matrix is not transposed, isIncidenceMatrix=true; otherwise, isIncidenceMatrix=false.
int h3pj[]={2, 5, 11, 13};//The ID numbers of places in H_l(p_max) for h_BDD where j is started from 1.
int h3_0=112; //h_BDD(S_0), =16*7
int P_R[]={14, 15, 16, 17, 18, 19}; //The IDs of resource places, started from 1.
*/

/*
char source_net[50]="ChenFig588";  //The name of the Petri net.
#define NP 21  //number of places!
#define NT 14  //number of transitions!
#define MAXNUMBER 255 // the largest number of the totol makespan, tokens in a place, remaining time in a place, and the ID of a transition.
#define MAXBITS 8 // the number of bits representing the above information such that MAXBITS=RoundUp(log_2(MAXNUMBER+1)).
const bool isIncidenceMatrix = false;  //If the inputed incidence matrix is not transposed, isIncidenceMatrix=true; otherwise, isIncidenceMatrix=false.
int h3pj[]={2, 5, 11, 13};//The ID numbers of places in H_l(p_max) for h_BDD where j is started from 1.
int h3_0=128; //h_BDD(S_0), =16*8
int P_R[]={14, 15, 16, 17, 18, 19}; //The IDs of resource places, started from 1.
*/


/*
char source_net[50]="ChenFig6111";  //The name of the Petri net.
bool isIncidenceMatrix = true;  //If the inputed incidence matrix is not transposed, isIncidenceMatrix=true; otherwise, isIncidenceMatrix=false.
#define NP 29  //number of places!
#define NT 20  //number of transitions!
#define MAXNUMBER 255 // the largest number of the totol makespan, tokens in a place, remaining time in a place, and the ID of a transition.
#define MAXBITS 8 // the number of bits representing the above information such that MAXBITS=RoundUp(log_2(MAXNUMBER+1)).
int h3pj[]={2, 4, 17};//The ID numbers of places in H_l(p_max) for h_BDD where j is started from 1.
int h3_0=11; //h_BDD(S_0), 11=11*1
int P_R[]={20, 21, 22, 23, 24, 25, 26}; //The IDs of resource places, started from 1.
*/



char source_net[50]="ChenFig6222";  //The name of the Petri net.
bool isIncidenceMatrix = true;  //If the inputed incidence matrix is not transposed, isIncidenceMatrix=true; otherwise, isIncidenceMatrix=false.
#define NP 29  //number of places!
#define NT 20  //number of transitions!
#define MAXNUMBER 255 // the largest number of the totol makespan, tokens in a place, remaining time in a place, and the ID of a transition.
#define MAXBITS 8 // the number of bits representing the above information such that MAXBITS=RoundUp(log_2(MAXNUMBER+1)).
int h3pj[]={2, 4, 17};//The ID numbers of places in H_l(p_max) for h_BDD where j is started from 1.
int h3_0=22; //h_BDD(S_0), 11=11*2
int P_R[]={20, 21, 22, 23, 24, 25, 26}; //The IDs of resource places, started from 1.



/*
char source_net[50]="ChenFig63117";  //The name of the Petri net.
bool isIncidenceMatrix = true;  //If the inputed incidence matrix is not transposed, isIncidenceMatrix=true; otherwise, isIncidenceMatrix=false.
#define NP 29  //number of places!
#define NT 20  //number of transitions!
#define MAXNUMBER 1023 // the largest number of the totol makespan, tokens in a place, remaining time in a place, and the ID of a transition.
#define MAXBITS 10 // the number of bits representing the above information such that MAXBITS=RoundUp(log_2(MAXNUMBER+1)).
int h3pj[]={2, 4, 17};//The ID numbers of places in H_l(p_max) for h_BDD where j is started from 1.
int h3_0=0; //h_BDD(S_0), 32=16*6!!!!!!!!!!!
int P_R[]={20, 21, 22, 23, 24, 25, 26}; //The IDs of resource places, started from 1.
*/

/*
char source_net[50]="Chen2011Big11111";  //The name of the Petri net.
bool isIncidenceMatrix = false;  //If the inputed incidence matrix is not transposed, isIncidenceMatrix=true; otherwise, isIncidenceMatrix=false.
#define NP 53  //number of places!
#define NT 38  //number of transitions!
#define MAXNUMBER 1023 // the largest number of the totol makespan, tokens in a place, remaining time in a place, and the ID of a transition.
#define MAXBITS 10 // the number of bits representing the above information such that MAXBITS=RoundUp(log_2(MAXNUMBER+1)).
int h3pj[]={2, 17, 34, 36};//The ID numbers of places in H_l(p_max) for h_BDD where j is started from 1.!!!!!!!!!!!!!
int h3_0=22; //h_BDD(S_0)!!!!!!!!!!!
int P_R[]={37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48}; //The IDs of resource places, started from 1.
*/

/*
char source_net[50]="Chen2011Big11112";  //The name of the Petri net.
bool isIncidenceMatrix = false;  //If the inputed incidence matrix is not transposed, isIncidenceMatrix=true; otherwise, isIncidenceMatrix=false.
#define NP 53  //number of places!
#define NT 38  //number of transitions!
#define MAXNUMBER 1023 // the largest number of the totol makespan, tokens in a place, remaining time in a place, and the ID of a transition.
#define MAXBITS 10 // the number of bits representing the above information such that MAXBITS=RoundUp(log_2(MAXNUMBER+1)).
int h3pj[]={2, 17, 34, 36};//The ID numbers of places in H_l(p_max) for h_BDD where j is started from 1.
int h3_0=32; //h_BDD(S_0)
int P_R[]={37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48}; //The IDs of resource places, started from 1.
*/

/*
char source_net[50]="Chen2011Big11212";  //The name of the Petri net.
bool isIncidenceMatrix = false;  //If the inputed incidence matrix is not transposed, isIncidenceMatrix=true; otherwise, isIncidenceMatrix=false.
#define NP 53  //number of places!
#define NT 38  //number of transitions!
#define MAXNUMBER 1023 // the largest number of the totol makespan, tokens in a place, remaining time in a place, and the ID of a transition.
#define MAXBITS 10 // the number of bits representing the above information such that MAXBITS=RoundUp(log_2(MAXNUMBER+1)).
int h3pj[]={2, 17, 34, 36};//The ID numbers of places in H_l(p_max) for h_BDD where j is started from 1.
int h3_0=39; //h_BDD(S_0)
int P_R[]={37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48}; //The IDs of resource places, started from 1.
*/

/*
char source_net[50]="Chen2011Big11122";  //The name of the Petri net.
bool isIncidenceMatrix = false;  //If the inputed incidence matrix is not transposed, isIncidenceMatrix=true; otherwise, isIncidenceMatrix=false.
#define NP 53  //number of places!
#define NT 38  //number of transitions!
#define MAXNUMBER 1023 // the largest number of the totol makespan, tokens in a place, remaining time in a place, and the ID of a transition.
#define MAXBITS 10 // the number of bits representing the above information such that MAXBITS=RoundUp(log_2(MAXNUMBER+1)).
int h3pj[]={2, 17, 34, 36};//The ID numbers of places in H_l(p_max) for h_BDD where j is started from 1.
int h3_0=32; //h_BDD(S_0)
int P_R[]={37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48}; //The IDs of resource places, started from 1.
*/


/*
char source_net[50]="Mine33";  //The name of the Petri net.
bool isIncidenceMatrix = true;  //The input incidence matrix is not transposed.
#define NP 14  //number of places!
#define NT 10  //number of transitions!
#define MAXNUMBER 127 // the largest number of the totol makespan, tokens in a place, remaining time in a place, and the ID of a transition.
#define MAXBITS 7 // the number of bits representing the above information such that MAXBITS=RoundUp(log_2(MAXNUMBER+1)).
*/


/*
char source_net[50]="MT10";  // a 10x10 source net, its optimal makespan is 930.
bool isIncidenceMatrix = false;  //If the inputed incidence matrix is not transposed, isIncidenceMatrix=true; otherwise, isIncidenceMatrix=false.
#define NP 130  //number of places!
#define NT 110  //number of transitions!
#define MAXNUMBER 10000 // the largest number of the totol makespan, tokens in a place, remaining time in a place, and the ID of a transition.
#define MAXBITS 14 // the number of bits representing the above information such that MAXBITS=RoundUp(log_2(MAXNUMBER+1)).
int h3pj[]={2, 4, 17};//The ID numbers of places in H_l(p_max) for h_BDD where j is started from 1.
int h3_0=0; //h_BDD(S_0), 32=16*6!!!!!!!!!!!
*/

/*
char source_net[50]="LA01";  // a 10x5 source net, its optimal makespan is 930.
bool isIncidenceMatrix = false;  //If the inputed incidence matrix is not transposed, isIncidenceMatrix=true; otherwise, isIncidenceMatrix=false.
#define NP 75  //number of places!
#define NT 60  //number of transitions!
#define MAXNUMBER 5000 // the largest number of the totol makespan, tokens in a place, remaining time in a place, and the ID of a transition.
#define MAXBITS 13 // the number of bits representing the above information such that MAXBITS=RoundUp(log_2(MAXNUMBER+1)).
int h3pj[]={4, 11, 17, 25, 34, 39, 45, 55, 60, 65};//The ID numbers of places in H_l(p_max) for h_BDD where j is started from 1.!!!!!!!!!!!!!
int h3_0=666; //h_BDD(S_0), 32=16*6!!!!!!!!!!!
*/

/*
char source_net[50]="LA02";  // a 10x5 source net, its optimal makespan is 930.
bool isIncidenceMatrix = false;  //If the inputed incidence matrix is not transposed, isIncidenceMatrix=true; otherwise, isIncidenceMatrix=false.
#define NP 75  //number of places!
#define NT 60  //number of transitions!
#define MAXNUMBER 5000 // the largest number of the totol makespan, tokens in a place, remaining time in a place, and the ID of a transition.
#define MAXBITS 13 // the number of bits representing the above information such that MAXBITS=RoundUp(log_2(MAXNUMBER+1)).
int h3pj[]={3, 13, 20, 27, 32, 40, 46, 54, 62, 68};//The ID numbers of places in H_l(p_max) for h_BDD where j is started from 1.!!!!!!!!!!!!!
int h3_0=635; //h_BDD(S_0), 32=16*6!!!!!!!!!!!
*/

/*
char source_net[50]="LA03";  // a 10x5 source net, its optimal makespan is 930.
bool isIncidenceMatrix = false;  //If the inputed incidence matrix is not transposed, isIncidenceMatrix=true; otherwise, isIncidenceMatrix=false.
#define NP 75  //number of places!
#define NT 60  //number of transitions!
#define MAXNUMBER 5000 // the largest number of the totol makespan, tokens in a place, remaining time in a place, and the ID of a transition.
#define MAXBITS 13 // the number of bits representing the above information such that MAXBITS=RoundUp(log_2(MAXNUMBER+1)).
int h3pj[]={2, 10, 20, 26, 32, 39, 48, 52, 62, 66};//The ID numbers of places in H_l(p_max) for h_BDD where j is started from 1.!!!!!!!!!!!!!
int h3_0=588; //h_BDD(S_0), 32=16*6!!!!!!!!!!!
*/

// Note that tfrom is the number of the fired place, beginning with number 0.  (Not used!)
//*********************************************************************************************************************

const int number_var_bigM = 3*NP+1;




bdd open;
bdd closed;

bdd et[NT];
bdd haveRemainTime[NT];

char resultFile[50];
ofstream outfile;
ifstream infile;

int initial_marking[NP];  //the initial marking
int final_marking[NP]; //the goal marking
int D[NP];  //operation times for all places

int rM[NP][NT]; //incidence matrix
int rIM[NT][NP]; //transposed incidence matrix (rIM, not rM!)

int loopNo;




bvec F;
bvec M[NP];  //M[i] = bvec_varfdd(i); //P82; after using fdd_extdomain(); 
bvec R1[NP];
bvec R2[NP]; // It can handle the nets whose operation places are at most 2-bounded.



struct schedulingState
{
	int f;
	int mu[NP]; //represents \mu in the pseudo code of the paper
	int r1[NP]; //the remaining processing time of the fisrt token in every place
	int r2[NP]; //the remaining processing time of the second token in every place
}; //do not forget the semicolon



struct stateD
{
	schedulingState s; //scheduling state
	int d; //remaining time to reversely reach the state s
}; //do not forget the semicolon

stateD sd; //BddToAStateHandler() will use sd.


stateD BackT(bdd, schedulingState, schedulingState, int);
bdd Constraints(schedulingState, int, int, int);
bool IsInitial(schedulingState);
bool IsResource(int); //whether or not p_i+1 is a resource place





void InitMarking()  //Constructs initial_marking, D, and final_marking from xxx_init.txt.
{
	char inputFile[50];
	strcpy(inputFile, source_net);
	strcat(inputFile, "_init.txt");			
	ifstream fin(inputFile);
        string str_init;
        int i=0;
        while(fin >> str_init && i<3*NP)
        {
		if(i<NP)
		        initial_marking[i]=atoi(str_init.c_str());		 	
		else if(i>=NP && i<2*NP)		
			D[i-NP]=atoi(str_init.c_str());				
		else
			final_marking[i-2*NP]=atoi(str_init.c_str());	
		i++;
        }
}


void InitMatrix() //Constructs incidence matrix rM from xxx_matrix.txt.
{
	char inputFile[50];
	strcpy(inputFile, source_net);
	strcat(inputFile, "_matrix.txt");
	ifstream fin(inputFile);
        string str_data;
        int i=0,j=0;
        while(fin >> str_data)
        {
                if(i == NP)
                {
                        break ;
                }
                rM[i][(j-i*NT)]=atoi(str_data.c_str());
                if(((j+1)%NT)==0 && j!=0)
                {
                        i++;
                }
                ++j;
        }
}

void TransposeMatrix()  //Constructs transposed incidence matrix rIM from rM since this program uses the transposed matrix rIM.
{
	for(int i=0;i<NP;i++)
	{
		for(int j=0;j<NT;j++)
		{
			rIM[j][i] = rM[i][j];
		}
	}	
}


void InitTransposedMatrix() //When xxx_matrix.txt contains a transposed incidence matrix derived from INA, extracts the transposed incidence matrix rIM.
{
	char inputFile[50];
	strcpy(inputFile, source_net);
	strcat(inputFile, "_matrix.txt");
	ifstream fin(inputFile);
        string str_data;
        int i=0,j=0;
        while(fin >> str_data)
        {
                if(j == NT)
                {
                        break ;
                }
                rIM[j][(i-j*NP)]=atoi(str_data.c_str());
                if(((i+1)%NP)==0 && i!=0)
                {
                        j++;
                }
                i++;
        }
}



bdd SubtractOne(bdd from,bdd B,int n,int a[])  //A recursive function for bit borrow.  a[] stores the positions of the bits of a place. B=bddtrue denotes subtracting 1; B=bddfalse denotes not. At the beginning, n=0.  //Note that the addition and subtraction in bits are more efficient than those in bvec. (11111)_2 and (31)_10
//It seems that the result can be a negative number.
{
        bdd var,var1,var2,tmp1,tmp2,f1,f2,b1,b2,r;

        if(from == bddfalse)
                return bddfalse;        
        if(B == bddfalse)  //if need not to substract 1.
                return from;        

        if(n == MAXBITS-1) //if the calculation is being applied to the highest bit
        { 
                var = bdd_ithvar(a[n]);
                tmp1 = bdd_constrain(from,var);
                f1 = bdd_and(bdd_not(var),tmp1);
                return f1;
        }
        else
        {
                var = bdd_ithvar(a[n]);
                tmp1 = bdd_constrain(from,var);		
                if(tmp1 != bddfalse)
                {
                        f1 = bdd_and(bdd_not(var),tmp1);
                        b1 = bddfalse;
                }
                else
                        f1 = bddfalse;
                
                tmp2 = bdd_constrain(from,bdd_not(var));
			
                if(tmp2 != bddfalse)
                {
                        f2 = bdd_and(var,tmp2);
                        b2 = bddtrue;
                }
                else
                        f2 = bddfalse;
                        
                n++;
                var1 = SubtractOne(f1,b1,n,a);
                var2 = SubtractOne(f2,b2,n,a);
                r = bdd_or(var1,var2);
                
                return r;
        }
}

bdd AddOne(bdd from,bdd B,int n,int a[])  //A recursive function for bit carry. a[] stores the positions of the bits of a place. B=bddtrue denotes adding 1; B=bddfalse denotes not. n=0
{
        bdd var,var1,var2,tmp1,tmp2,f1,f2,b1,b2,r;
        if(from == bddfalse)  //if there is no addend.
                return bddfalse;
        if(B == bddfalse)
                return from;
        
        if(n == MAXBITS-1) //if the calculation is being applied to the highest bit
        { 
                var = bdd_ithvar(a[n]);
                tmp1 = bdd_constrain(from,bdd_not(var));
                f1 = bdd_and(var,tmp1);
                return f1;
        }
        else
        {
                var = bdd_ithvar(a[n]);
                tmp1 = bdd_constrain(from,bdd_not(var));
                if(tmp1 != bddfalse)
                {
                        f1 = bdd_and(var,tmp1);
                        b1 = bddfalse;
                }
                else
                        f1 = bddfalse;
                
                tmp2 = bdd_constrain(from,var);
                if(tmp2 != bddfalse)
                {
                        f2 = bdd_and(bdd_not(var),tmp2);
                        b2 = bddtrue;
                }
                else
                        f2 = bddfalse;
                
                n++;
                var1 = AddOne(f1,b1,n,a);
                var2 = AddOne(f2,b2,n,a);
                r=bdd_or(var1,var2);

                return r;
        }
}




void  AllsatPrintHandler(char* varset, int size)  //Size is the number of bits for each marking. Use bdd_allsat(bdd r, AllsatPrintHandler) to print all markings.
//cout<<fddset<<from<<endl and fdd_printset(bdd) have a similar result to that of bdd_allsat(from, AllsatPrintHandler).
//This function may dispaly some strange info.
{
	int f_dec=0;	
	int M_dec[NP], R1_dec[NP], R2_dec[NP];
	for(int i=0;i<MAXBITS;i++)
	{
		f_dec += varset[i*number_var_bigM]*(int)pow(2,i);		
	}
	for(int n=0;n<NP;n++)
	{
		M_dec[n]=R1_dec[n]=R2_dec[n]=0;
		for(int i=0;i<MAXBITS;i++)
		{
			M_dec[n] += varset[n+1+i*number_var_bigM]*(int)pow(2,i);
			R1_dec[n] += varset[n+NP+1+i*number_var_bigM]*(int)pow(2,i);
			R2_dec[n] += varset[n+2*NP+1+i*number_var_bigM]*(int)pow(2,i);
		}
	}

	outfile<<"<f="<<abs(f_dec)<<", M=(";	
	for(int n=0;n<NP-1;n++)		
		outfile<<abs(M_dec[n])<<", ";
		
	outfile<<abs(M_dec[NP-1])<<"), R1=(";
	for(int n=0;n<NP-1;n++)		
		outfile<<abs(R1_dec[n])<<", ";
		
	outfile<<abs(R1_dec[NP-1])<<"), R2=(";
	for(int n=0;n<NP-1;n++)		
		outfile<<abs(R2_dec[n])<<", ";
				
	outfile<<abs(R2_dec[NP-1])<<")>"<<endl;	
	
}




void  BddToAStateHandler(char* varset, int size)  //Size is the number of bits for each marking. Use bdd_allsat(bdd r, BddToAStateHandler) to transform a bdd r to sd.s. Note that when use r=bdd_fullsatone(found) please ensure that there is only one state in the bdd.
{
	int f_dec=0;	
	int M_dec[NP], R1_dec[NP], R2_dec[NP];
	for(int i=0;i<MAXBITS;i++)
	{
		f_dec += varset[i*number_var_bigM]*(int)pow(2,i);		
	}
	for(int n=0;n<NP;n++)
	{
		M_dec[n]=R1_dec[n]=R2_dec[n]=0;
		for(int i=0;i<MAXBITS;i++)
		{
			M_dec[n] += varset[n+1+i*number_var_bigM]*(int)pow(2,i);
			R1_dec[n] += varset[n+NP+1+i*number_var_bigM]*(int)pow(2,i);
			R2_dec[n] += varset[n+2*NP+1+i*number_var_bigM]*(int)pow(2,i);
		}
	}
	
	sd.s.f=abs(f_dec);
	
	for(int i=0;i<NP;i++)
	{
		sd.s.mu[i]=abs(M_dec[i]);
		sd.s.r1[i]=abs(R1_dec[i]);
		sd.s.r2[i]=abs(R2_dec[i]);	
	}		
}


//h_BDD(S_0)
//decide if Place x is in the vector h3pj
bool IsInH3pj(int x)
{
	int n_h3pj=sizeof(h3pj)/sizeof(h3pj[0]); //IMPORTANT!!!!
	for(int n=0; n<n_h3pj;n++)
		if(x==h3pj[n])
			return true;
	return false;
}



bdd Img(bdd from, int hmethod) //To generate a set of submarkings of from
{
        bdd generatedMarkings = bddfalse;
	bdd markingsEnableTi; //the markings that enable t_i.
	bdd result_tmp;
	
	
	// et[i]: This constraint represents that t_i is enalbed. It is for a marking set.
	// haveRemainTime[i]: This constraint represents that there exists a remaining time in any pre-place of t_i. It is for a marking set.
	for(int i=0;i<NT;i++) //t_i     
	{
		et[i] = bddtrue;  //It is a constraint. It is for a marking set.
		haveRemainTime[i] = bddfalse; //It is a constraint. It is for a marking set.
		for(int j=0;j<NP;j++) //p_j
			if(rIM[i][j] < 0) //p_j->t_i
			{
				et[i] &= bvec_gte(M[j],bvec_con(MAXBITS,1)); // Note that the weight of an arc is always 1. Thus, it is for ordinary nets.
				if(D[j]!=0)  //only consider activity pre-places of t_i.
				{
					haveRemainTime[i] |= bvec_equ(M[j], bvec_con(MAXBITS, 1)) & (bvec_gth(R1[j],bvec_con(MAXBITS,0)) | bvec_gth(R2[j],bvec_con(MAXBITS,0))); 
					haveRemainTime[i] |= bvec_equ(M[j], bvec_con(MAXBITS, 2)) & bvec_gth(R1[j],bvec_con(MAXBITS,0)) & bvec_gth(R2[j],bvec_con(MAXBITS,0));
				}
			}
	}
        
        
        for(int i=0;i<NT;i++)  //for each transition t_i
        {   	
        	
		markingsEnableTi = from & et[i]; //et[i]: the condition under which t_i is enabled at a marking. It only handles the markings that are in From and enable t_i.
				
                if(markingsEnableTi!=bddfalse)  // Here, cannot use markingsEnableTi==bddtrue!
                {   

		        bdd tmp1, tmp2;
        		int a[MAXBITS];        		
        		
                	             	
                	//11111111111111111. Subtract remaining processing time in each t_i's pre-place, and add the corresponding time to "f" (f=g+h).
			//Delta is the maximal remaining processing time among all places p\in ^{\bullet} t_i.                	
                	//Subtract delta from Mr and add it to f.  //The method is to iteratively subtract one from each Mr if any pre-post of the transition has a remaining processing time.
                	//Add delta to f       
                	//Handle h.
                	// (F, M, R1, R2)            	                	

		        tmp1 = markingsEnableTi & haveRemainTime[i];  //t_i
		        
		        result_tmp = markingsEnableTi - tmp1;
		        
		        
		        
		         //For all markings that have a remain time to fire t_i, subtract 1 from each place whose remain process time is greater than 0 until t_i is ready to fire and add 1 to f at each iteration.
		        while(tmp1 != bddfalse) // While there exists some pre-places of t_j whose Mr > 0 (consider different tokens in a place), then subtractOneFromAllMr and addOneToF. tmp1 contains markings that have remaining time in some places to fire t_i.
		        {        	    
		        	for(int j=0;j<NP;j++)  //R1 and R2 of all activity places will be subtracted by one if they are greater than 0.
		        		if(D[j]>0)
			        	{
			        		//It costs most of the calculation time!!!!!!!!!!!!!!!!!!!!!!!
			        		
			        		//subtract 1 from R1 of all activity places if their R1>0.//
			        		//Uses SubtractOne() when the minuend is greater than 0. Mr cannot be negative.
			        		bdd tmp1_gt0 = tmp1 & bvec_gth(R1[j],bvec_con(MAXBITS,0));
			        		
			        		
			        		if (tmp1_gt0!=bddfalse) 
			        		{
			        			tmp1 = tmp1-tmp1_gt0;
			        			
				        		for(int s=0;s<MAXBITS;s++)        
		                                		a[s]=j+1+NP+s*number_var_bigM;       //R1[j]   
		                                	tmp1_gt0 = SubtractOne(tmp1_gt0,bddtrue,0,a);//R1[j]-- 
		                                	
		                                	if(hmethod==3 && IsInH3pj(j+1))//f(M')=f(M)+c(M,M')+h(M')-h(M),here perform h(M')-h(M) for h_BDD
		                                	{
		                                		//Subtract 1 from f.		
						        	for(int s=0;s<MAXBITS;s++)        
				                                	a[s]= s*number_var_bigM;  //f                        
				                                tmp1_gt0 = SubtractOne(tmp1_gt0,bddtrue,0,a);  //f--
		                                	}
		                                	
		                                	tmp1 |= tmp1_gt0;
	                                	}
	                                	

	                                	
	                                	tmp1_gt0 = tmp1 & bvec_gth(R2[j],bvec_con(MAXBITS,0));
			        		
			        		
	                                	if (tmp1_gt0 != bddfalse)
			        		{
			        			tmp1 = tmp1-tmp1_gt0;
			        			
		                                	for(int s=0;s<MAXBITS;s++)        
		                                		a[s]=j+1+2*NP+s*number_var_bigM;        //R2[j]                        
		                                	tmp1_gt0 = SubtractOne(tmp1_gt0,bddtrue,0,a);   //R2[j]--
		                                	
		                                	if(hmethod ==3 && IsInH3pj(j+1))//f(M')=f(M)+w(M,M')+h(M')-h(M),here perform h(M')-h(M) for h_BDD
		                                	{
		                                		//Subtract 1 from f.
						        	for(int s=0;s<MAXBITS;s++)        
				                                	a[s]= s*number_var_bigM;  //f                        
				                                tmp1_gt0 = SubtractOne(tmp1_gt0,bddtrue,0,a);  //f--
		                                	}
		                                	
		                                	tmp1 |= tmp1_gt0;
		                                }      
		                                
			        	}// for(int j=0;j<NP;j++)          	
		        	
		        	
                                      	
		        	// Add 1 to f.
		        	for(int s=0;s<MAXBITS;s++)        
                                	a[s]= s*number_var_bigM;  //f                        
                                tmp1 = AddOne(tmp1,bddtrue,0,a);  //f++
                                
					
                                tmp2 = tmp1 & haveRemainTime[i];  //t_i
                                result_tmp |= (tmp1 - tmp2);  
                                tmp1 = tmp2;         
                                
                                		        	
		        }//while(tmp1 != bddfalse)     
		               
		       
			if (hmethod==1) //h=t_depth-1; h_0=12
	                	//...........f(M)+h(M')-h(M); h=depth-1 when the fired t is a post-transition of an activity place. 
	                	if (i==2 ||i==4 ||i==6 ||i==8 ||i==10 ||i==12 ||i==14 ||i==16 ||i==18 || i==20 ||i==22 ||i==24)
	                	{
	                		int a[MAXBITS];  //the value is the number of bits to represent a place
	                                for(int s=0;s<MAXBITS;s++)        
	                                        	a[s]=s*number_var_bigM;                                   
	                                                
	                                result_tmp = SubtractOne(result_tmp,bddtrue,0,a);
	                	}
                	
                	
                	
                	// 2222222222222222. Move tokens. 
         		for(int j=0;j<NP;j++)  //p_j
         		{ 
                                if(rIM[i][j] < 0)   //If some tokens should be removed from some pre-places of a transition due to the firing of the transition. rIM: transposed incidence matrix. Note that it only handles the ordinary nets.
                                {  
                                        int a[MAXBITS];  //MAXBITS is the number of bits representing a place
                                        for(int s=0;s<MAXBITS;s++)        
                                        	a[s]=j+1+s*number_var_bigM; //The positions of bits for tokens in a place.               
						//Note that fdd_extdomain(int* dom, int num) extends the set of finite domain blocks with the NP domains in dom. Each domain allocates log_2(dom[i]) BDD variables. The ordering of BDD variables is interleaved.
                                        result_tmp = SubtractOne(result_tmp,bddtrue,0,a);//result_tmp is the operated BDD; bddtrue denotes subtracting 1; "a" stores the positions of bits for places. It handles all markings in a set. 
                                        
                                        //Uses bvec_add() and bvec_sub(). They can automatically carry and borrow bits.
                                        //However, operations on bits are more efficient than on bvec.
                                            
                                }
                                if(rIM[i][j] > 0) // if some tokens should be added to places
                                { 
                                        int a[MAXBITS];
                                        for(int s=0;s<MAXBITS;s++)
                                        	a[s]=j+1+s*number_var_bigM;
               
					result_tmp = AddOne(result_tmp,bddtrue,0,a);					
                                }
                        }
                        
                	
                	//333333333333333: Add the operation times to R1 or R2 of post-places of t_i. 
                	//The current version is for the nets whose activity places is at most 2-bounded. It can be revised for other cases.
                	//Only one token will be added into an activity place by firing a transition in the considered nets.
                	//It can be revised for generality by adding an operation time to the first zero entry.
                	bdd R,tmp3;
                	bdd result_3=bddfalse;
                	
                	
                	for(int j=0;j<NP;j++) //p_j
                	{         
		         	if(rIM[i][j] > 0 && D[j]!=0) //t_i-> p_j and p_j is an activity place.
		         	{
		         		
		         		//Case 1: R1[j]<=0.
		         		R = bvec_lte(R1[j], bvec_con(MAXBITS, 0));  //constraint: R1[j]<=0
		         		tmp1 = result_tmp & R;		 //constraint: R1[j]<=0
		         		
		         		//Case 2: R1[j]>0.
		         		R = bvec_gth(R1[j], bvec_con(MAXBITS, 0));  //constraint: R1[j]>0
		         		tmp2 = result_tmp & R;		//constraint: R1[j]>0
		         		
		         		
		         		if(tmp1 != bddfalse)
		         		{
		         			result_tmp = result_tmp - tmp1;
		         			
		         			tmp1=bdd_exist(tmp1, fdd_ithset(j+1+NP)); //P34: Remove all occurences in 1# of the variables in 2# by an existential quantification.
		         			tmp1 &= fdd_ithvar(j+1+NP,D[j]);//Then R1[j]=D[j]
		         			
		         			result_tmp |= tmp1;		         			
		         		}  
		         		
		         		
		         		if(tmp2 != bddfalse)
		         		{
		         			result_tmp = result_tmp - tmp2;
		         			
		         			tmp2=bdd_exist(tmp2, fdd_ithset(j+1+2*NP));
		         			tmp2 &= fdd_ithvar(j+1+2*NP,D[j]); //Then R2[j]=D[j]
		         			
		         			result_tmp |= tmp2;		         			
		         		} 
		         		
		         	}//if(rIM[i][j] > 0 && D[j]!=0)
		         }//for(int j=0;j<NP;j++) //p_j	 
		             
                	                	
                        generatedMarkings |= result_tmp;
                        
                        
                }//if(markingsEnableTi!=bddfalse) 
                
        }//for(int i=0;i<NT;i++)   t_i
        
        return generatedMarkings;
}




int Traverse(string choice, int hmethod)  //Search a path in the state space.  If it finds a path with the Astar algorithm, then return the final f value; if it finds a path with BFS, return 0; if exits with failure, return -1.
{
	
	bdd R_Mt =bddtrue;  //M in bigM is restricted to the final marking.	
	for(int i=0;i<NP;i++)
		R_Mt  &= fdd_ithvar(i+1,final_marking[i]);  //P86, fdd_ithvar() returns a BDD that defines the value 2# for the finite domain block 1#.	
	
	loopNo=1;  //A global variable for debugging.	
	
	bdd from, R, found;
	bdd succ = bddfalse ; 	
	
	
	//Breadth First Search
	if(choice=="BFS" || choice=="bfs")
		while(1)
		{
			if(display_least==false)
			{
				cout<<"=====================loopNo:"<<loopNo<<"====================="<<endl;
				cout<<"Number of markings in open: "<<bdd_satcount(open)<<endl;	//bdd_satcount() will not affect the running speed greatly.	
				if(display_debug==true)
				{
					bdd_allsat(open, AllsatPrintHandler);
					cout<<endl;					
				}
			}
			
			if(open == bddfalse)
		        {
		                cout<<"OPEN is NULL! No path can be found!!"<<endl;
		                return -1;               
		        } 	
	
			found = open & R_Mt; //Note that we should not use succ & R_Mt!!
			if(found!= bddfalse)  //Finds the markings whose marking is Mt, i.e., if OPEN contains Mt. OPEN consists of 2N*2 interleaved FDD variables.
			{
			                	cout<<"A result has been found for the NET: "<<source_net<<"."<<endl;
			                	cout<<"Format of fdd_printset(found): <0:f, 1-"<<NP<<":M, "<<NP+1<<"-"<<2*NP<<":R1, "<<2*NP+1<<"-"<<3*NP<<":R2>"<<endl;
			                	cout<<fddset<<found<<endl;
			                	
			                	
			                	if(writeFile==true)
			                	{
				                	outfile<<"A result has been found for the NET: "<<source_net<<"."<<endl;
				                	outfile<<"Format of fdd_printset(found): <0:f, 1-"<<NP<<":M, "<<NP+1<<"-"<<2*NP<<":R1, "<<2*NP+1<<"-"<<3*NP<<":R2>"<<endl;
				                	outfile<<fddset<<found<<endl;
			                	}

			                	
			                	
			                	
			                	if(display_least==false)
			                	{		               		
			                		cout<<"Mt(bdd_allsat)=";
			                		bdd_allsat(found, AllsatPrintHandler); //It becomes more clear, but it may display wrong info.
			                		cout<<endl;
			                	
			                	
			                		cout<<"----------open------bdd_satcount(open):"<<bdd_satcount(open)<<endl;
			                		fdd_printset(open);
			                		cout<<endl;
			                		cout<<"----------found-----bdd_satcount(found):"<<bdd_satcount(found)<<endl;
			                		fdd_printset(found);
			                		cout<<endl;
			                	}

			                	
			                	
			                    	return 0;               
			} 
			
			
			closed |= open; //To compute the number of explored states.
			open = Img(open, hmethod);  // At the very beginning, from only contains M0.
			
			loopNo++;         

		}//while(1)	
	
	else if(choice=="Astar" || choice=="astar")
	{
		int least_f=0; //since we use a consistent heuristic, so the f-values are non-decreasing.
		while(1)
		{
			if(open == bddfalse)
		        {
		                cout<<"Open is NULL! No path can be found!!"<<endl;
		                return -1;               
		        } 		        		        
		
			for(int f_scan=least_f;;f_scan++)
			{					        
			        if(display_least==false)
			        {
				        cout<<"=====================loopNo:"<<loopNo<<", f_scan: "<<f_scan<<"====================="<<endl;
					cout<<"Number of markings in OPEN: "<<bdd_satcount(open)<<endl;		
					cout<<"Number of markings in CLOSED: "<<bdd_satcount(closed)<<endl;	
				}				
				
				R = fdd_ithvar(0, f_scan);		
				from = open & R;				
				
				if(from != bddfalse)
				{
					least_f=f_scan;  //since we use a consistent heuristic, so the f-values are non-decreasing.
					
					found = from & R_Mt; //Note that we should not use succ & R_Mt!!
			        	if(found!= bddfalse)  //Finds the states whose marking is Mt, i.e., if OPEN contains Mt; OPEN consists of 2N*2 interleaved FDD variables.
			        	{			
				     		
			                	
			                	cout<<"A result has been found for the NET: "<<source_net<<"."<<endl;
			                	cout<<"Format of fdd_printset(found): <0:f, 1-"<<NP<<":M, "<<NP+1<<"-"<<2*NP<<":R1, "<<2*NP+1<<"-"<<3*NP<<":R2>"<<endl;
			                	cout<<fddset<<found<<endl;
			                	
			                	if(writeFile==true)
			                	{
				                	outfile<<"A result has been found for the NET: "<<source_net<<"."<<endl;
				                	outfile<<"Format of fdd_printset(found): <0:f, 1-"<<NP<<":M, "<<NP+1<<"-"<<2*NP<<":R1, "<<2*NP+1<<"-"<<3*NP<<":R2>"<<endl;
				                	outfile<<fddset<<found<<endl;
			                	}
			                	
			                	
			                	if(display_least==false)
			                	{
			                		cout<<"Mt(bdd_allsat)=";
			                		bdd_allsat(found, AllsatPrintHandler);//It becomes more clear, but it may display wrong info.
			                		cout<<endl;
			                	}		                
			                	
			                    	return least_f;               
			         	} 		
					
					
					
					if(display_debug==true && display_least==false)
					{
						cout<<"loopNo:"<<loopNo<<"--------"<<endl;
						cout<<"Number of markings in from: "<<bdd_satcount(from)<<endl;						
						bdd_allsat(from, AllsatPrintHandler);
					}
					
					
					succ = Img(from, hmethod);  // At the very beginning, FROM only contains M0.

					
					
					closed |= from;	
					succ=succ-closed; 
					
					if(display_debug==true && display_least==false)
					{
						cout<<"loopNo:"<<loopNo<<"--------"<<endl;
						cout<<"Number of new markings in succ: "<<bdd_satcount(succ)<<endl;
						bdd_allsat(succ, AllsatPrintHandler);
						cout<<endl;
					}
					open = open - from;
					open |= succ;
					
					from = open & R; //Use the same f_scan. if it generates new markings with the same f value.
					
					loopNo++;
					
					break;  //Break the FOR structure. Only if from==bddfalse, then f_scan++ in FOR.				     
			        }//if(from != bddfalse)	    			        			     

			}//for(int f_scan=least_f;;f_scan++)
		}//while(1)
	}//else if(choice=="Astar" || choice=="astar")
	else
	{
		cout<<"The parameter of hmethod is wrong!"<<endl;
		return -1;
	}
}




int Search(string choice, int hmethod, int h0)  // Obtians a path from a given initial marking to a given goal marking via an A* search
{
	int i ;
	
	static int dom[number_var_bigM]; //const int number_var_bigM = 3*NP+1; (F,M,R1,R2)
	for(int i=0;i<number_var_bigM;i++)
		dom[i]= MAXNUMBER; //#define MAXNUMBER 255 // the largest number of the totol makespan, tokens in a place, remaining time in a place, and the ID of a transition.
	
	
	bdd_init(10000000,1000000);
	fdd_extdomain(dom,number_var_bigM);  //P84, Extends the set of finite domain blocks with the NP domains in dom. Each domain allocates log_2(dom[i]) BDD variables. The ordering of the BDD variables is interleaved.
	
		
	
	// renames the elements in bigM=(F,M,R1,R2).  
	F=bvec_varfdd(0);
	for(i=0;i<NP;i++)
		M[i] = bvec_varfdd(i+1); //bvec M[NP]  // P82,build a Boolean vector that includes exactly the variables to define the FDD variable block i.
	for(i=0;i<NP;i++)
		R1[i] = bvec_varfdd(i+NP+1);
	for(i=0;i<NP;i++)
		R2[i] = bvec_varfdd(i+2*NP+1);
		
	
	bdd M0_big=bddtrue; // the initial marking (F,M,R1,R2)
	M0_big &= fdd_ithvar(0,h0);  // f(M_0)=h0;
		
	for(i=0;i<NP;i++) // M(M_0)=the initial marking; R1(M_0)=0; R2(M_0)=0;
	{
		M0_big &= fdd_ithvar(i+1,initial_marking[i]); //P86  Returns the BDD that defines the value initial_marking[i] for the finite domain block i+1. Do not operate a bdd with a fdd by using &=.
		M0_big &= fdd_ithvar(i+NP+1,0); //R1
		M0_big &= fdd_ithvar(i+2*NP+1,0); //R2
	}
		
	
	
	cout<<"cout<<fddset<<M0_big:"<<endl;
	cout<<fddset<<M0_big<<endl;
	cout<<endl;
	
	if(writeFile==true)
	{
		outfile<<"M0_big (bdd_allsat):"<<endl;
		bdd_allsat(M0_big, AllsatPrintHandler);
		outfile<<endl;
	}

	
		
	open = bddfalse;
	open |= M0_big;  // At the very beginning, only M0 is in OPEN.
	
	if(writeFile==true)
	{
		outfile<<"Number of scheduling states in OPEN at the beginning: "<<bdd_satcount(open)<<endl;	
		outfile<<"Number of scheduling states in OPEN at the beginning (logarithm in base 2): "<<bdd_satcountln(open)<<endl;
	}

	return Traverse(choice, hmethod);
	
}

int ite_No; 

//Extract a path from s_G to s_0 in CLOSED and print it. For its psedocode, please refer to PathConstruct.pdf. 
void Construct(bdd closed, schedulingState s_0, schedulingState s_G)
{
	int path_length=100;
	int path[path_length][2];
	
	//stateT St_pre;
	//initialization
	for(int i=0;i<path_length;i++) 
	{
		for(int j=0;j<2;j++)
		{
			path[i][j]=0;
		}
	}	
	
	ite_No=0; //ite_No represents e in the pseudo code.
	schedulingState s_p=s_G; //s_p represents s' in the pseudocode.
	int g_reversed=0;
	
	
	while(IsInitial(s_p)==false) //if it does not reach the initial state.
	{
		cout<<"Iteration: "<<ite_No<<endl;
		if(writeFile==true)
		{		
			outfile<<endl;
			outfile<<"=========================================================================="<<endl;
			outfile<<"Iteration: "<<ite_No<<endl;
			outfile<<"The f-value of the current state (i.e., s in the pseudocode): ";
			outfile<<"f="<<s_p.f<<endl;
			
			for(int i=0;i<NP;i++)
			{
				if(s_p.mu[i]>0)
					outfile<<"mu("<<i+1<<"):"<<s_p.mu[i]<<", ";
			}
			for(int i=0;i<NP;i++)
			{
				if(s_p.r1[i]>0)
					outfile<<"r1("<<i+1<<"):"<<s_p.r1[i]<<", ";
			}
			for(int i=0;i<NP;i++)
			{
				if(s_p.r2[i]>0)
					outfile<<"r2("<<i+1<<"):"<<s_p.r2[i]<<", ";
			}
			outfile<<endl;
		}
	
	
		schedulingState s=s_p;
		
		//Looks for the transitions revsersly enabled at s (considering Ri) 
		bool rEt[NT]; //whether t is reversely enabled at marking s_G
		
		if(writeFile == true)        
			outfile<<"Reversely enabled transitions at the current state (i.e., s in the pseudocode): ";
			
		for(int j=0; j<NT; j++)
		{
			rEt[j]=true;	
			for(int i=0; i<NP; i++)
			{
				if(rIM[j][i]>0 && s.mu[i]<rIM[j][i] || rIM[j][i]>0 && s.mu[i]>=rIM[j][i] && s.r1[i]<D[i] && s.r2[i]<D[i]) //the arc weight is 1
				{
					rEt[j]=false;
					break;
				}
				
			}
			if(rEt[j]==true && writeFile == true)
				outfile<<j+1<<"  ";			
						
		}
		if(writeFile == true) 		
			outfile<<endl<<endl;	
		
		for(int j=0;j<NT;j++)
		{
			if(rEt[j]==true)
			{
				stateD sd=BackT(closed,s_0,s,j); //j begins with 0; 
				s_p=sd.s;
				if(s_p.f!=-1)  //if a predecessor state is found in Closed.
				{			
					path[ite_No][0]=s_G.f-g_reversed;
					path[ite_No][1]=j;	
					if(writeFile == true) 
						outfile<<"path["<<ite_No<<"]: g="<<path[ite_No][0]<<", t="<<path[ite_No][1]+1<<endl;
					g_reversed+=sd.d;
					ite_No++;
					break; 
				}

			}
		}
	
	
	}//while(IsInitial(s_p)==false) 
	
	
	
	//print the path
	cout<<endl;
	cout<<"The scheduling path:"<<endl;
	for(int i=ite_No-1;i>=0;i--)
		cout<<ite_No-i<<": (g="<<path[i][0]<<", t=t_"<<path[i][1]+1<<");"<<endl;
	
	
	if(writeFile==true)
	{
		outfile<<endl;
		outfile<<"The scheduling path:"<<endl;
		for(int i=ite_No-1;i>=0;i--)	
			outfile<<ite_No-i<<": (g="<<path[i][0]<<", t=t_"<<path[i][1]+1<<");"<<endl;			

	}
	
	return;
	
}

//Decide whether or not s equals the initial state
bool IsInitial(schedulingState s)
{
	for(int i=0;i<NP;i++)
		if(s.mu[i]!=initial_marking[i])
			return false;
	return true;
}


//Decide whether or not p_i+1 is a resource place
bool IsResource(int i)
{
	int count_resource=sizeof(P_R)/sizeof(P_R[0]); //IMPORTANT!!!!
	for(int k=0; k<count_resource;k++)
		if(i+1==P_R[k]) //P_R[k] starts from 1.
			return true;
	return false;
}


//Reversely fire t from (s, t_{t+1}) to s' in CLOSED. d is the decreased time to reach s'. Note that s' depends on not only t but also t' that is reversely enabled at s'. s'.f=-1 means no satisfied state in Closed.
//Note that s'.mu and s'.f are decided by t, but s'.r is also decided by t' that is reversely enabled at s'!!!
stateD BackT(bdd closed, schedulingState s_0, schedulingState s, int t)  // t starts from 0.
{
	//Token moving for the reversly firing of t for all places
	for(int i=0;i<NP;i++)
	{
		if(rIM[t][i]>0)
			s.mu[i]=s.mu[i]-rIM[t][i]; //use the transposed incidence matrix rIM
		if(rIM[t][i]<0)
			s.mu[i]=s.mu[i]-rIM[t][i];
	}
	
	
	if(IsInitial(s)==true)
	{
		sd.s=s_0;
		sd.d=0;  
		return sd;
	}
	
	
	
	//Handle the remaining times of tokens in the activity post-place of t. There exists at most one such place.
	for(int i=0;i<NP;i++)
	{
		if(rIM[t][i]>0 && D[i]>0)
		{
			if(s.r2[i]==D[i])
				s.r2[i]=0;
			else
				s.r1[i]=0;
		}
	}
	
	//Handle r1 and r2 of other activity places
	schedulingState s_p=s; //s_p denotes s'

	
	
	bool rEt[NT]; //whether or not t is reversely enabled at a marking s_p
	
	
	if(writeFile==true)
	{
		outfile<<endl;
		outfile<<"-------------------------------------------------------------------------"<<endl;
		outfile<<"The selected enabled transition at the current state (i.e., s):"<<endl;
		outfile<<"t="<<t+1<<endl;
		outfile<<"Reversely enabled transitions at the marking of preceding state (i.e., s'.mu): "<<endl;
		outfile<<"t'=";	
		
	}
		
	for(int j=0; j<NT; j++)
	{
		rEt[j]=true;	
		for(int i=0; i<NP; i++)
			if(rIM[j][i]>0 && s_p.mu[i]<rIM[j][i])
			{
				rEt[j]=false;		
				continue;
			}	
		if(rEt[j]==true && writeFile==true)
			outfile<<j+1<<"  ";	//Note that t starts from 1 for debugging!			
	}
	if(writeFile==true)
	{
		outfile<<endl;
		outfile<<"-------------------------------------------------------------------------"<<endl;
	}
	
	for(int j=0;j<NT;j++)
	{		
		if(rEt[j]==true)
		{
			bdd C=bddtrue; //Donot use true or bddfalse!!!
			
			//Constraints of M.
			for(int i=0;i<NP;i++)
				C &= bvec_equ(M[i], bvec_con(MAXBITS,s_p.mu[i]));
			
			
			int d,p_p,p_pp; //d is the time required for p_p to reversely enable t_{j+1} at s_p; p_p denotes p' and p_pp denotes p'' in the psuedo code.
			if(writeFile==true)
				outfile<<"t'=t_"<<j+1<<endl;
				
			for(int i=0;i<NP;i++)
			{
				if(rIM[j][i]>0 && initial_marking[i]==0) //initial_marking[i]=0	means P_A + end places. In the reversely firing, end places may be excluded.  D[i] are allowed to be 0. 
				{
					p_p=i;
					break; //Only one such place p_{i+1}.
				}
			}
			if(writeFile==true)			
				outfile<<"p'=p_"<<p_p+1<<endl;
			
			
			for(int i=0;i<NP;i++)
			{
				if(rIM[t][i]<0 && IsResource(i)==false) //initial_marking[i]=0	 means P_A + end places. In the reversely firing, end places may be excluded.  D[i] are allowed to be 0. 					
				{
					p_pp=i;
					break; //Only one such place p_{i+1}.
				}
			}	
			if(writeFile==true)		
				outfile<<"p''=p_"<<p_pp+1<<endl;
			
				
			
			
			
			int maxRp_p, maxRp_pp;
			if(s_p.r1[p_p]>=s_p.r2[p_p])
				maxRp_p=s_p.r1[p_p];
			else
				maxRp_p=s_p.r2[p_p];
				
			if(s_p.r1[p_pp]>=s_p.r2[p_pp])
				maxRp_pp=s_p.r1[p_pp];
			else
				maxRp_pp=s_p.r2[p_pp];
				
				
				
			d=D[p_p]-maxRp_p;  //d is the time required for p_p to reversely enable t_{j+1} at s'. To reach the situation after 33333333333.
			if(writeFile==true)
				outfile<<"d="<<d<<endl;
				
			if(d>D[p_pp]-maxRp_pp)
			{	
				if(writeFile==true)
				{
					outfile<<"d>D[p_pp]-maxRp_pp!!!!!!!!!!!!!!!!!!!!!!"<<endl;
					outfile<<"--------------"<<endl;
				}
				continue;
			}
			
			
			if(D[p_p]==0 || maxRp_p>0 || p_p==p_pp)
				C &= Constraints(s_p, p_p, p_pp, d);
			else
			{
				bdd C1 = bddfalse;
				for(int k=0; k<=D[p_pp]-maxRp_pp-d; k++)
					C1 |= Constraints(s_p, p_p, p_pp, d+k);
				C &= C1;
			}
				
				
			//Try to find a state that satisfies C in Closed.
			bdd found = closed & C; 

			
			if(found != bddfalse)
			{
				//for debugging
				if(writeFile==true)
				{
					outfile<<"p': p_"<<p_p+1<<endl;					
					outfile<<"d: "<<d<<endl;
					
					outfile<<"-------------------"<<endl;
					outfile<<"The number of satisfied states for C in CLOSED. bdd_satcount(found): "<<bdd_satcount(found)<<endl;
					outfile<<"They are: "<<fddset<<found<<endl;
					outfile<<"-------------------"<<endl;
				}
				
				bdd S_p=bdd_fullsatone(found);	//Note that S_p is a BDD. Do not use bdd_satone() since it may get more than one marking.	
				outfile<<"The number of states in S_p: "<<bdd_satcount(S_p)<<endl;
						
				bdd_allsat(S_p, BddToAStateHandler); //Transform S_p to sd.s by using BddToAStateHandler.	Uses abs()
				
				if(writeFile==true)
				{
					outfile<<"A satisfied state found in CLOSED:"<<endl;
					outfile<<"bdd_allsat(S_p, AllsatPrintHandler): ";					
					bdd_allsat(S_p, AllsatPrintHandler); //for debug
					outfile<<endl;
					
					outfile<<"outfile<<fddset<<S_p<<endl:";
					outfile<<fddset<<S_p<<endl<<endl;
				}
				
				
				int maxR, minR;				
				if(sd.s.mu[p_pp]==1)
				{
					if(sd.s.r1[p_pp]>=sd.s.r2[p_pp])	
						maxR=sd.s.r1[p_pp];
					else
						maxR=sd.s.r2[p_pp];
					sd.d=maxR;
				}
				else //sd.s.mu[p_pp]==2
				{
					if(sd.s.r1[p_pp]<=sd.s.r2[p_pp])	
						minR=sd.s.r1[p_pp];
					else
						minR=sd.s.r2[p_pp];
					sd.d=minR;
				}
				
				if(writeFile==true)
					outfile<<"The value of d is: "<<sd.d<<endl;
					
				return sd;				
			}//if(found != bddfalse)				
			
		}//if(rEt[j]==true)		
		
	}//for(int j=0;j<NT;j++)
	
	//cout<<"Cannot find any satisfied state in CLOSED!!!"<<endl;  //for Debug	
	sd.s.f=-1; //f=-1 means no satisfied state in Closed.
	sd.d=0;  
	return sd;
	
}
			
			
			
//Constraints of F and R for the state s' such that s'[t>s whose time is d, \exists s'', s''[t>s', p' is the activity post-place of t', and p'' is the non-resource pre-place of t.
bdd Constraints(schedulingState s_p, int p_p, int p_pp, int d)			
{
			
			//Constraints for F.			
			int l=-1; //l is used to denote whether or not there is a loyal activity place that has tokens. If there is one (only one), l denotes its index which starts from 0, otherwise, l=-1.
			
			
			//Do not use "for(int i=0;i<NP && s_p.mu[i]>0 && D[i]>0;i++)" since i++ will only be executed after the for body is performed.
			
				
			int N_loyal= sizeof(h3pj)/sizeof(h3pj[0]);  //obtain the number of elements in h3pj.
			for(int i=0;i<NP;i++)
			{
				if(s_p.mu[i]>0 && D[i]>0)
				{
					for(int k=0;k<N_loyal;k++)
						if(i+1==h3pj[k])  //The index of h3pj starts from 1.
							l=i; //at most one such place
				}
			}
			
			if(writeFile==true)
			{
				outfile<<"l=p_"<<l+1<<endl;
				outfile<<"----------------"<<endl;
			}

			
			bdd C = bddtrue;
			if(l==-1)  //l==-1 means there is no such a place.
				C &= bvec_equ(F, bvec_con(MAXBITS,s_p.f-d));				
			else if(l==p_pp)  //if it is the activity post-place of t'.
				C &= bvec_equ(F, bvec_con(MAXBITS,s_p.f));
			else //if it is an activity place other than the output one.
			{
				if(s_p.r1[l]>0 || s_p.r2[l]>0)
					C &= bvec_equ(F, bvec_con(MAXBITS,s_p.f));
				else //r1[l]=r2[l]=0
				{					
						int a=0;
						bdd C1=bddfalse;
						while(a<=d)
						{
							if(a==0)
								C1 |=  bvec_equ(F, bvec_con(MAXBITS,s_p.f-d)) & bvec_equ(R1[l], bvec_con(MAXBITS,0)) & bvec_equ(R2[l], bvec_con(MAXBITS,0));  //Note that for l
							else							
								C1 |=  bvec_equ(F, bvec_con(MAXBITS,s_p.f-d+a)) & ( bvec_equ(R1[l], bvec_con(MAXBITS,a)) | bvec_equ(R2[l], bvec_con(MAXBITS,a)));  
							a++;
						}
						C &= C1;					
					
				}
				
			}
				
			//Constraints of R in p', i.e., p_p.
			C &= bvec_equ(R1[p_p], bvec_con(MAXBITS,D[p_p])) | bvec_equ(R2[p_p], bvec_con(MAXBITS,D[p_p]));
			
			
			//Constraints of R in p'', i.e., p_pp.
			if(D[p_pp]>0)  //Since p'' may be a start place or an activity place with D=0.
			{
				if(s_p.mu[p_pp]==1)
				{
					
						if(d>0)
							C &= bvec_equ(R1[p_pp], bvec_con(MAXBITS,d)) | bvec_equ(R2[p_pp], bvec_con(MAXBITS,d));
						if(d==0)
							C &= bvec_equ(R1[p_pp], bvec_con(MAXBITS,0)) & bvec_equ(R2[p_pp], bvec_con(MAXBITS,0));
										
				}
				else  //s_p.mu[p_pp]==2
				{					
						C &= bvec_equ(R1[p_pp], bvec_con(MAXBITS,s_p.r1[p_pp]+d));
						C &= bvec_equ(R2[p_pp], bvec_con(MAXBITS,s_p.r2[p_pp]+d));
				}
			}
			
			
			//Constraints of R in other acitivity places.
			for(int i=0;i<NP;i++) 
			{
				if(s_p.mu[i]>0 && D[i]>0 && i!=p_p && i!=p_pp)
				{
					if(s_p.mu[i]==1)
					{
							if(s_p.r1[i]>0)
								C &= bvec_equ(R1[i], bvec_con(MAXBITS,s_p.r1[i]+d)) & bvec_equ(R2[i], bvec_con(MAXBITS,0));
							else if(s_p.r2[i]>0)
								C &= bvec_equ(R2[i], bvec_con(MAXBITS,s_p.r2[i]+d)) & bvec_equ(R1[i], bvec_con(MAXBITS,0));
							else
								C = C & ( bvec_lte(R1[i], bvec_con(MAXBITS,d)) & bvec_equ(R2[i], bvec_con(MAXBITS,0)) | bvec_lte(R2[i], bvec_con(MAXBITS,d)) & bvec_equ(R1[i], bvec_con(MAXBITS,0)));
					}
					else //s_p.mu[i]==2
					{
							if(s_p.r1[i]>0)
								C &= bvec_equ(R1[i], bvec_con(MAXBITS,s_p.r1[i]+d));
							else
								C &= bvec_lte(R1[i], bvec_con(MAXBITS,d));
							
							if(s_p.r2[i]>0)
								C &= bvec_equ(R2[i], bvec_con(MAXBITS,s_p.r2[i]+d));
							else
								C &= bvec_lte(R2[i], bvec_con(MAXBITS,d));
						
					}				
				}	
				
			}//for(int i=0;i<NP;i++) 
			
			
			return C;
}			




int main()
{	
	cout<<"--------------------------------------------------------------------------------------------------------------------"<<endl;
	cout<<"--------------------------Bo Huang, Nanjing University of Science and Technology, China-----------------------------"<<endl;
	cout<<"---------------------------------------------huangbo@njust.edu.cn---------------------------------------------------"<<endl;
	cout<<"--------------------------------------------------------------------------------------------------------------------"<<endl;
	cout<<"-----This program is to search a scheduling path from a given initial marking (state) to a given final marking of a place-timed Petri"<<endl;
	cout<<"-----net of FMSs by using BDDs. Before running it, create a file of incidence matrix (netname_matrix.txt) and a file of initial marking"<<endl; 	
	cout<<"-----, operation time, as well as final marking (netname_init.txt) in the same folder as the executable file of the program. "<<endl; 
	cout<<"-----It searches via BFS or the A* algorithm with a selected heuristic function that can be specified by Search() in main()."<<endl;
	cout<<"-----Its outputs results in Console and result.txt. The suggested platform is Centos+Buddy."<<endl;
	cout<<"-----The current version can deal with the ordinary nets whose activity places are at most 2-bounded."<<endl;
	cout<<"-----For more info., please refer to Bo Huang, MengChu Zhou. Supervisory Control and Scheduling of Resource Allocation Systems--Reachability Graph Perspective. Wiley-IEEE Press. 2020."<<endl;
	cout<<"--------------------------------------------------------------------------------------------------------------------"<<endl;

        cout<<"========================================================================================"<<endl;
	cout<<"ver1.1 (20170606_Bo_Huang):"<<endl;
	cout<<"----------------------------------------------------------------------------------------"<<endl;
	cout<<"1. Add comments;"<<endl;
	cout<<"2. Make the program more readable by revising variable names and output results;"<<endl;
	cout<<"3. Debug it for speed;"<<endl;	
	cout<<"4. When applied to a new net, change NP, NT, MAXNUMBER and MAXBITS at the beginning of the program;"<<endl;
 	cout<<"----------------------------------------------------------------------------------------"<<endl;
 	cout<<"ver2.0 (20170622_Bo_Huang):"<<endl;
	cout<<"----------------------------------------------------------------------------------------"<<endl;
	cout<<"1. Revise for A* search with f=0;"<<endl;
	cout<<"2. Each element in (F,M,R1,R2) has the same number of bits;"<<endl;
	cout<<"3. Rename some variables and functions;"<<endl;	
 	cout<<"----------------------------------------------------------------------------------------"<<endl;
 	cout<<"ver2.1 (20170707_Bo_Huang):"<<endl;
	cout<<"----------------------------------------------------------------------------------------"<<endl;
	cout<<"1. Define the constant int number_var_bigM =  3*NP+1;"<<endl;
	cout<<"2. It is for non-decreasing f;"<<endl;
	cout<<"3. Remove tfrom and Closed;"<<endl;
	cout<<"4. Add switch for debugging: const bool display_debug;"<<endl;
	cout<<"========================================================================================"<<endl;
	cout<<"ver2.2 (201707_Bo_Huang):"<<endl;
	cout<<"----------------------------------------------------------------------------------------"<<endl;
	cout<<"1. Add h, hmethod=0(h=0); hmethod=1(t_step-1, inadmissible);"<<endl;
	cout<<"2. Add BFS(breadth first search)!"<<endl;
	cout<<"3. Add hmethod=3(e_{Maxi}, admissible, consistent), which needs the detailed vector h3pj and h(S_0)!"<<endl;
	cout<<"4. Astar is for consistent h since f is considered to be non-decreasing!"<<endl;
	cout<<"========================================================================================"<<endl;
	cout<<"ver2.3 (201710_Bo_Huang):"<<endl;
	cout<<"----------------------------------------------------------------------------------------"<<endl;
	cout<<"1. Add CLOSED to compute the number of expanded nodes and exclude the expanded nodes from OPEN."<<endl;
	cout<<"2. Use bdd_printset() to replace bdd_allsat() in the display of results."<<endl;
	cout<<"========================================================================================"<<endl;
	cout<<"ver2.4 (20171121_Bo_Huang):"<<endl;
	cout<<"----------------------------------------------------------------------------------------"<<endl;
	cout<<"1. Add Construct() to find an optimal path in CLOSED and print it;"<<endl;
	cout<<"2. pro_time[] is replaced by D[];"<<endl;
	cout<<"========================================================================================"<<endl;
	cout<<"ver2.5 (20171207_Bo_Huang):"<<endl;
	cout<<"----------------------------------------------------------------------------------------"<<endl;
	cout<<"1. Revise Construct() to avoid deadend;"<<endl;
	cout<<"2. Rename variables according to the book;"<<endl;
	cout<<"3. Output debug info to result.txt;"<<endl;
	cout<<"========================================================================================"<<endl;
	cout<<"ver2.6 (20200208_Bo_Huang):"<<endl;
	cout<<"----------------------------------------------------------------------------------------"<<endl;
	cout<<"1. Comments have been polished;"<<endl;
	cout<<"2. Input files of different nets have been updated;"<<endl;
	cout<<"3. The pseudocode of the program has been uploaded;"<<endl;
	cout<<"========================================================================================"<<endl;
	
	cout<<endl<<endl;
	
	struct timeval start,finish;  
	double totalTime;
	int optimal_f;
	
	writeFile=true;  //!!!!!!!!!!!!!!!
	
	
	if(writeFile == true)
	{
	        outfile.open("result.txt");	
	        outfile<<"Start searching..."<<endl<<endl;
	}
		
	

		cout<<"Start searching..."<<endl;
		InitMarking();
		
		//This program uses a transposed incidence matrix.
		if(isIncidenceMatrix==true)
		{
			InitMatrix();	
			TransposeMatrix();
			//initCoInverseMatrix();
		}
		else
			InitTransposedMatrix();  
		
		
			
		
		//string choice = DisplayAndChoose();  
		
		//If you want to display the least info, use debug=false and least=true. 
		display_debug = false; //output the debug info.
		display_least = true; //output the least info.
		
		writeFile = true; //output the backtracking info to result.txt
		
		
		
		
		
	     	gettimeofday(&start,NULL);  				
	        
		//************************************************************************
		//Parameters of Search():
		//Parameter 1# (string, search method): "BFS" means breadth first search; "Astar" means A* search; 
		//Parameter 2# (hmethod)(int, If P1="BFS", P2 should be 0; If P1="Astar", P2 represents hmethod: 0 means h=0; 1 means h=t_depth-1 (Using post-transitions of operational places); 3 means h=e_{Maxi};  Note that h_BDD uses Search("Astar", 3, h3_0);
		//Parameter 3# (h0)(int, FOR Astar; 0 when P1="BFS"): if hmethod=0, then h0=0; if hmethod =1, then h0=12 or else t_depth; if hmethod =2, then h0=0; if hmethod=3, then h0=h3_0, it needs the given vector h3pj in the net descritions.
		//************************************************************************
		
		//Search("BFS",0, 0); //Use it and disable the rest if use Breadth First Search.
		//Search("Astar",0, 0); //Use it and disable the rest if use h=0 in Astar.
		optimal_f=Search("Astar", 3, h3_0);  //Use it and disable the rest if use h=h_BDD in Astar. Note that only Astar return optimal f values.	        
	        
	        gettimeofday(&finish,NULL);  
	     	totalTime = finish.tv_sec - start.tv_sec + (finish.tv_usec - start.tv_usec) / 1000000.0;  
	     	
	     	
	  
	     	//cout<<"Your choice is: "<<choice<<endl;	
	     	
	     	//fdd_printset(open);
	     	//bdd_allsat(open, AllsatPrintHandler);
	     	cout<<endl;
	     	cout<<"-----------------------------------------"<<endl;
	     	cout<<"Search time: "<<totalTime<<" seconds."<<endl;       	
	     	cout<<"The number of scheduling states (F,M,R1,R2) in CLOSED:"<<bdd_satcount(closed)<<endl;
	     	cout<<"The number of scheduling states (F,M,R1,R2) in CLOSED (logarithm in base 2):"<<bdd_satcountln(closed)<<endl;
	     	cout<<"The number of BDD Nodes for CLOSED:"<<bdd_nodecount(closed)<<endl<<endl; 	
	     	cout<<"Start backtracking..."<<endl;
	     	
	     	if(writeFile == true)
	     	{
		     	outfile<<endl;
		     	outfile<<"-----------------------------------------"<<endl;
		     	outfile<<"Search time: "<<totalTime<<" seconds."<<endl;       	
		     	outfile<<"The number of scheduling states (F,M,R1,R2) in CLOSED:"<<bdd_satcount(closed)<<endl;
		     	outfile<<"The number of scheduling states (F,M,R1,R2) # in CLOSED (logarithm in base 2):"<<bdd_satcountln(closed)<<endl;
		     	outfile<<"The number of BDD Nodes for CLOSED:"<<bdd_nodecount(closed)<<endl<<endl; 
		     	outfile<<"Start backtracking..."<<endl;	
	     	}
     	

     	
     	// Find a path in CLOSED
     	schedulingState s_0, s_G;
     	s_0.f=h3_0; //!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
     	s_G.f=optimal_f; 

     	
     	for(int i=0;i<NP;i++)
     	{
     		s_0.mu[i]=initial_marking[i];
     		s_G.mu[i]=final_marking[i];
     		s_0.r1[i]=s_0.r2[i]=s_G.r1[i]=s_G.r2[i]=0;
     	}     	
     	
     	
     	gettimeofday(&start,NULL);        
        Construct(closed, s_0, s_G);
        gettimeofday(&finish,NULL);  
        
     	totalTime = finish.tv_sec - start.tv_sec + (finish.tv_usec - start.tv_usec) / 1000000.0;          
        cout<<"Backtracking time: "<<totalTime<<" seconds."<<endl;  
        
        if(writeFile == true)
        {		
		outfile<<"Backtracking time: "<<totalTime<<" seconds."<<endl;  
		outfile.close();
		
		cout<<"Result.txt has been succesfully generated!!!"<<endl;
	}
        
	return 0;	
}
